USE [master]
GO
CREATE DATABASE [SimpleDatabase]
GO
ALTER DATABASE [SimpleDatabase] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SimpleDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SimpleDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SimpleDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SimpleDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SimpleDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SimpleDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [SimpleDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SimpleDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SimpleDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SimpleDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SimpleDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SimpleDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SimpleDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SimpleDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SimpleDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SimpleDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SimpleDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SimpleDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SimpleDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SimpleDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SimpleDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SimpleDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SimpleDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SimpleDatabase] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SimpleDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [SimpleDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SimpleDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SimpleDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SimpleDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SimpleDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SimpleDatabase]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Logs](
    [LogId] [int] IDENTITY(1,1) NOT NULL,
    [Message] nvarchar(300) NOT NULL,
    [PublishDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Logs] PRIMARY KEY CLUSTERED 
(
    [LogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [SimpleDatabase] SET  READ_WRITE 
GO
