//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdChat.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ConnectionStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConnectionStrings defaultInstance = ((ConnectionStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConnectionStrings())));
        
        public static ConnectionStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://admin:telerik@ds035280.mongolab.com:35280/crowdchat")]
        public string MongoDbCloudServer {
            get {
                return ((string)(this["MongoDbCloudServer"]));
            }
            set {
                this["MongoDbCloudServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crowdchat")]
        public string MongoDbDefaultDatabase {
            get {
                return ((string)(this["MongoDbDefaultDatabase"]));
            }
            set {
                this["MongoDbDefaultDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://localhost")]
        public string MongoDbLocalServer {
            get {
                return ((string)(this["MongoDbLocalServer"]));
            }
            set {
                this["MongoDbLocalServer"] = value;
            }
        }
    }
}
