-- SEARCH WITHOUT FULL-TEXT
CHECKPOINT; DBCC DROPCLEANBUFFERS; -- Empty the SQL Server cache
SELECT * FROM Logs
WHERE Message LIKE '%329'
GO

-- SEARCH WITHOUT FULL-TEXT
CHECKPOINT; DBCC DROPCLEANBUFFERS; -- Empty the SQL Server cache
SELECT * FROM Logs
WHERE Message LIKE 'Mess%'
GO

-- SEARCH WITHOUT FULL-TEXT
CHECKPOINT; DBCC DROPCLEANBUFFERS; -- Empty the SQL Server cache
SELECT * FROM Logs
WHERE Message LIKE '%322%'
GO

-- SEARCH WITH FULL-TEXT
CHECKPOINT; DBCC DROPCLEANBUFFERS; -- Empty the SQL Server cache
SELECT * FROM Logs
WHERE CONTAINS(Message,'1256789')
GO

-- CREATE FULL TEXT CATALOG
CREATE FULLTEXT CATALOG MessagesFullTextCatalog
WITH ACCENT_SENSITIVITY = OFF

CREATE FULLTEXT INDEX ON Logs([Message])
KEY INDEX PK_Logs
ON MessagesFullTextCatalog
WITH CHANGE_TRACKING AUTO

-- DROP FULLTEXT CATALOG MessagesFullTextCatalog
-- DROP FULLTEXT INDEX ON Logs